import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { createAdminClient } from "@/lib/supabase/admin";
import { isCultureIntelligenceV2Enabled } from "@/lib/env";

export default async function AuditLogsPage(){const admin=createAdminClient();const [events,suggestions,runs,movements]=await Promise.all([
 admin.from("culture_event_audit_log").select("id,action,actor_id,created_at,culture_event:culture_events(title)").order("created_at",{ascending:false}).limit(50),
 isCultureIntelligenceV2Enabled() ? admin.from("culture_suggestion_audit_log").select("id,action,actor_type,actor_id,created_at,suggestion:culture_event_suggestions(title)").order("created_at",{ascending:false}).limit(50) : Promise.resolve({ data: [] }),
 admin.from("market_engine_v2_runs").select("id,tick_key,status,updated_count,skipped_count,error_count,started_at").order("started_at",{ascending:false}).limit(25),
 admin.from("market_engine_v2_calculations").select("id,asset_id,culture_event_id,final_percentage_move,reason,applied,calculated_at").eq("applied",true).order("calculated_at",{ascending:false}).limit(25),
]);return <div className="space-y-6"><PageHeader title="Audit Logs" description="Read-only AI suggestion decisions, CultureEvent actions and Market Engine v2 calculations."/><Card><h2 className="font-bold">AI suggestion audit</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Time</th><th>Action</th><th>Suggestion</th><th>Actor</th></tr></thead><tbody>{(suggestions.data??[]).map(row=><tr key={row.id} className="border-t border-border"><td className="py-2">{new Date(row.created_at).toLocaleString("en-GB")}</td><td>{row.action}</td><td>{(row.suggestion as unknown as {title?:string}|null)?.title??row.id}</td><td>{row.actor_type} <span className="font-mono text-xs">{row.actor_id??""}</span></td></tr>)}</tbody></table></div></Card><Card><h2 className="font-bold">CultureEvent audit</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Time</th><th>Action</th><th>Event</th><th>Actor</th></tr></thead><tbody>{(events.data??[]).map(row=><tr key={row.id} className="border-t border-border"><td className="py-2">{new Date(row.created_at).toLocaleString("en-GB")}</td><td>{row.action}</td><td>{(row.culture_event as unknown as {title?:string}|null)?.title??row.id}</td><td className="font-mono text-xs">{row.actor_id??"system"}</td></tr>)}</tbody></table></div></Card><Card><h2 className="font-bold">Engine runs</h2><div className="mt-3 space-y-2 text-sm">{(runs.data??[]).map(run=><div key={run.id} className="rounded-lg bg-surface-muted p-3"><b>{run.tick_key}</b> · {run.status} · {run.updated_count} updated · {run.skipped_count} skipped · {run.error_count} errors</div>)}</div></Card><Card><h2 className="font-bold">Applied movements</h2><div className="mt-3 space-y-2 text-sm">{(movements.data??[]).map(move=><div key={move.id} className="rounded-lg bg-surface-muted p-3"><b>{Number(move.final_percentage_move).toFixed(3)}%</b> · {move.reason}</div>)}</div></Card></div>}
