import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { createAdminClient } from "@/lib/supabase/admin";

export default async function EngineHealthPage(){const admin=createAdminClient();const [success,failed,latest,calcs]=await Promise.all([
  admin.from("market_engine_v2_runs").select("started_at,completed_at").eq("status","completed").order("started_at",{ascending:false}).limit(1).maybeSingle(),
  admin.from("market_engine_v2_runs").select("started_at,errors").eq("status","failed").order("started_at",{ascending:false}).limit(1).maybeSingle(),
  admin.from("market_engine_v2_runs").select("id,status,updated_count,skipped_count,seven_day_drift_percent,drift_warning,errors,started_at").order("started_at",{ascending:false}).limit(1).maybeSingle(),
  admin.from("market_engine_v2_calculations").select("final_percentage_move").order("calculated_at",{ascending:false}).limit(500),
]);const capBreaches=(calcs.data??[]).filter(row=>Math.abs(Number(row.final_percentage_move))>15).length;const rows=[["Last successful tick",success.data?.started_at?new Date(success.data.started_at).toLocaleString("en-GB"):"None"],["Last failed tick",failed.data?.started_at?new Date(failed.data.started_at).toLocaleString("en-GB"):"None"],["Assets updated",String(latest.data?.updated_count??0)],["Assets skipped",String(latest.data?.skipped_count??0)],["Seven-day median drift",`${Number(latest.data?.seven_day_drift_percent??0).toFixed(3)}%`],["Cap breaches",String(capBreaches)]];const warnings=[latest.data?.drift_warning,...(latest.data?.errors??[])].filter(Boolean) as string[];return <div className="space-y-6"><PageHeader title="Engine Health" description="Market Engine v2 execution, drift and safety telemetry."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(([label,value])=><Card key={label}><p className="text-xs text-muted">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></Card>)}</div><Card><h2 className="font-bold">Recent warnings and errors</h2>{warnings.length?<ul className="mt-3 space-y-2 text-sm text-loss">{warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul>:<p className="mt-2 text-sm text-muted">No warnings in the latest run.</p>}</Card></div>}
