import type { CultureEvent } from "@/lib/culture-intelligence/types";

const HOUR = 60 * 60 * 1000;

export function generateMockCultureEvents(now = new Date()): CultureEvent[] {
  const createdAt = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * HOUR).toISOString();

  return [
    {
      id: "11111111-1111-4111-8111-111111111111",
      title: "Dune teaser breaks franchise engagement record",
      description: "Manual mock event.", sourceName: "mock", sourceUrl: null, createdBy: null, isVerified: true,
      eventType: "release",
      affectedAssets: [{ slug: "dune", name: "Dune" }, { slug: "zendaya", name: "Zendaya" }],
      confidence: 0.94,
      expectedAttention: 72,
      predictedAttention: 89,
      sentiment: "positive",
      reach: 18400000,
      timeToPeakHours: 8,
      decayRate: 0.18,
      status: "verified",
      actualAttention: null,
      surpriseDelta: null,
      momentumScore: null,
      viralMultiplier: null,
      resolvedAt: null,
      source: "mock",
      createdAt: createdAt(3),
    },
    {
      id: "22222222-2222-4222-8222-222222222222",
      title: "Taylor Swift signals surprise project announcement",
      description: "Manual mock event.", sourceName: "mock", sourceUrl: null, createdBy: null, isVerified: false,
      eventType: "announcement",
      affectedAssets: [{ slug: "taylor-swift", name: "Taylor Swift" }],
      confidence: 0.78,
      expectedAttention: 86,
      predictedAttention: 81,
      sentiment: "mixed",
      reach: 32700000,
      timeToPeakHours: 14,
      decayRate: 0.11,
      status: "draft",
      actualAttention: null,
      surpriseDelta: null,
      momentumScore: null,
      viralMultiplier: null,
      resolvedAt: null,
      source: "mock",
      createdAt: createdAt(6),
    },
    {
      id: "33333333-3333-4333-8333-333333333333",
      title: "Liverpool completes dramatic stoppage-time comeback",
      description: "Manual mock event.", sourceName: "mock", sourceUrl: null, createdBy: null, isVerified: true,
      eventType: "sports_result",
      affectedAssets: [{ slug: "liverpool-fc", name: "Liverpool FC" }],
      confidence: 0.99,
      expectedAttention: 64,
      predictedAttention: 77,
      sentiment: "positive",
      reach: 12100000,
      timeToPeakHours: 2,
      decayRate: 0.31,
      status: "resolved",
      actualAttention: 5,
      surpriseDelta: 1.8,
      momentumScore: 84.6,
      viralMultiplier: 1.94,
      resolvedAt: createdAt(8),
      source: "mock",
      createdAt: createdAt(11),
    },
    {
      id: "44444444-4444-4444-8444-444444444444",
      title: "Netflix partnership rumour gathers trade press coverage",
      description: "Manual mock event.", sourceName: "mock", sourceUrl: null, createdBy: null, isVerified: false,
      eventType: "partnership",
      affectedAssets: [{ slug: "netflix", name: "Netflix" }],
      confidence: 0.61,
      expectedAttention: 48,
      predictedAttention: 55,
      sentiment: "neutral",
      reach: 4200000,
      timeToPeakHours: 30,
      decayRate: 0.09,
      status: "draft",
      actualAttention: null,
      surpriseDelta: null,
      momentumScore: null,
      viralMultiplier: null,
      resolvedAt: null,
      source: "mock",
      createdAt: createdAt(1),
    },
    {
      id: "55555555-5555-4555-8555-555555555555",
      title: "MrBeast challenge clip crosses global viral threshold",
      description: "Manual mock event.", sourceName: "mock", sourceUrl: null, createdBy: null, isVerified: true,
      eventType: "viral_moment",
      affectedAssets: [{ slug: "mrbeast", name: "MrBeast" }],
      confidence: 0.9,
      expectedAttention: 68,
      predictedAttention: 84,
      sentiment: "positive",
      reach: 24600000,
      timeToPeakHours: 5,
      decayRate: 0.27,
      status: "resolved",
      actualAttention: 4.5,
      surpriseDelta: 1.1,
      momentumScore: 75.2,
      viralMultiplier: 1.72,
      resolvedAt: createdAt(17),
      source: "mock",
      createdAt: createdAt(22),
    },
    {
      id: "66666666-6666-4666-8666-666666666666",
      title: "Zendaya awards-season win completes attention cycle",
      description: "Manual mock event.", sourceName: "mock", sourceUrl: null, createdBy: null, isVerified: true,
      eventType: "award",
      affectedAssets: [{ slug: "zendaya", name: "Zendaya" }],
      confidence: 0.97,
      expectedAttention: 75,
      predictedAttention: 74,
      sentiment: "positive",
      reach: 9800000,
      timeToPeakHours: 3,
      decayRate: 0.24,
      status: "resolved",
      actualAttention: 3,
      surpriseDelta: -0.75,
      momentumScore: 52.4,
      viralMultiplier: 1.2,
      resolvedAt: createdAt(93),
      source: "mock",
      createdAt: createdAt(96),
    },
  ];
}
