"use client";

import { useMemo, useState } from "react";
import { approveSuggestion, editSuggestion, mergeSuggestion, rejectSuggestion } from "@/actions/culture-suggestions";
import { Card } from "@/components/ui/card";
import type { DiscoveryMonitoring, SuggestedCultureEvent } from "@/lib/culture-intelligence/discovery-types";
import { CULTURE_EVENT_TYPES } from "@/lib/culture-intelligence/types";

const percent = (value: number) => `${Math.round(value * 100)}%`;

export function SuggestedEventsQueue({ suggestions, monitoring, enabled, assets }: { suggestions: SuggestedCultureEvent[]; monitoring: DiscoveryMonitoring; enabled: boolean; assets: Array<{ id: string; slug: string; name: string }> }) {
  const [status, setStatus] = useState("pending");
  const visible = useMemo(() => suggestions.filter((item) => status === "all" || item.status === status), [suggestions, status]);
  if (!enabled) return <Card><h2 className="font-bold">Suggested Events</h2><p className="mt-2 text-sm text-muted">AI discovery is safely disabled. Set FEATURE_CULTURE_INTELLIGENCE_V2=true after the migration, approved sources and API key are configured.</p></Card>;
  return <section id="suggested-events" className="space-y-4">
    <div><h2 className="text-xl font-bold">Suggested Events</h2><p className="text-sm text-muted">AI discoveries stay here until an admin approves them as unverified CultureEvent drafts.</p></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">
      {[["Suggestions today", monitoring.suggestionsToday], ["Approval rate", percent(monitoring.approvalRate)], ["Rejection rate", percent(monitoring.rejectionRate)], ["Average confidence", `${monitoring.averageConfidence.toFixed(0)}%`], ["Prediction accuracy", monitoring.averagePredictionAccuracy == null ? "Awaiting outcomes" : percent(monitoring.averagePredictionAccuracy)], ["Duplicate detection", percent(monitoring.duplicateDetectionRate)]].map(([label, value]) => <Card key={label} className="!p-3"><p className="text-xs text-muted">{label}</p><p className="mt-1 font-bold">{value}</p></Card>)}
    </div>
    <Card className="!p-4"><label className="text-sm font-semibold">Queue status <select value={status} onChange={(event) => setStatus(event.target.value)} className="ml-2 rounded-lg border border-border bg-surface px-3 py-2"><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="merged">Merged</option><option value="all">All</option></select></label></Card>
    <div className="space-y-3">
      {visible.map((suggestion) => <Card key={suggestion.id}>
        <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">AI suggestion · {suggestion.eventType.replaceAll("_", " ")}</p><h3 className="mt-1 text-lg font-bold">{suggestion.title}</h3><p className="mt-2 max-w-4xl text-sm text-foreground-secondary">{suggestion.summary}</p></div><span className="rounded-full bg-surface-muted px-3 py-1 text-xs font-bold capitalize">{suggestion.status}</span></div>
        <div className="mt-4 grid gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6"><Metric label="Assets" value={suggestion.affectedAssets.map((asset) => asset.name).join(", ")}/><Metric label="Confidence" value={`${suggestion.confidence.toFixed(0)}%`}/><Metric label="Expected" value={`${suggestion.expectedAttention}/5`}/><Metric label="Predicted" value={`${suggestion.predictedAttention}/5`}/><Metric label="Reach" value={`${suggestion.reach}/5`}/><Metric label="Impact preview" value={`${suggestion.estimatedPriceImpactPercent > 0 ? "+" : ""}${suggestion.estimatedPriceImpactPercent.toFixed(2)}%`}/></div>
        <details className="mt-4 rounded-lg bg-surface-muted p-3"><summary className="cursor-pointer font-semibold">AI reasoning and sources</summary><p className="mt-2 text-sm">{suggestion.reasoning}</p><ul className="mt-2 list-disc pl-5 text-sm">{suggestion.sourceLinks.map((source) => <li key={source.url}><a className="text-primary hover:underline" href={source.url} target="_blank" rel="noreferrer">{source.sourceName}: {source.title}</a></li>)}</ul></details>
        {suggestion.status === "pending" && <div className="mt-4 grid gap-3 lg:grid-cols-4">
          <form action={approveSuggestion} className="rounded-lg border border-border p-3"><input type="hidden" name="id" value={suggestion.id}/><input type="hidden" name="title" value={suggestion.title}/><input type="hidden" name="summary" value={suggestion.summary}/><label className="flex gap-2 text-xs"><input required type="checkbox" name="confirmation" value="APPROVE_AS_DRAFT"/>Approve as an unverified draft only</label><button className="mt-2 rounded bg-gain px-3 py-2 text-sm font-bold text-white">Approve</button></form>
          <details className="rounded-lg border border-border p-3"><summary className="cursor-pointer text-sm font-bold">Edit</summary><form action={editSuggestion} className="mt-2 space-y-2"><input type="hidden" name="id" value={suggestion.id}/><input name="title" defaultValue={suggestion.title} required className="w-full rounded border border-border bg-surface p-2 text-sm"/><textarea name="summary" defaultValue={suggestion.summary} required className="w-full rounded border border-border bg-surface p-2 text-sm"/><select name="event_type" defaultValue={suggestion.eventType} className="w-full rounded border border-border bg-surface p-2 text-sm">{CULTURE_EVENT_TYPES.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select><select name="affected_assets" multiple required defaultValue={suggestion.affectedAssets.map((asset) => asset.slug)} className="min-h-24 w-full rounded border border-border bg-surface p-2 text-sm">{assets.map((asset) => <option key={asset.id} value={asset.slug}>{asset.name}</option>)}</select><select name="sentiment" defaultValue={suggestion.sentiment} className="w-full rounded border border-border bg-surface p-2 text-sm">{["positive","neutral","negative","mixed"].map((value) => <option key={value}>{value}</option>)}</select><EditNumber name="confidence" label="Confidence %" value={suggestion.confidence} min={0} max={100}/><EditNumber name="expected_attention" label="Expected attention" value={suggestion.expectedAttention} min={1} max={5}/><EditNumber name="predicted_attention" label="Predicted attention" value={suggestion.predictedAttention} min={1} max={5}/><EditNumber name="reach" label="Reach" value={suggestion.reach} min={1} max={5}/><EditNumber name="time_to_peak_hours" label="Time to peak hours" value={suggestion.timeToPeakHours} min={0} max={720}/><EditNumber name="decay_rate" label="Decay rate" value={suggestion.decayRate} min={0} max={1} step={0.01}/><button className="rounded bg-primary px-3 py-2 text-sm font-bold text-white">Save edits</button></form></details>
          <form action={rejectSuggestion} className="rounded-lg border border-border p-3"><input type="hidden" name="id" value={suggestion.id}/><input name="reason" required placeholder="Rejection reason" className="w-full rounded border border-border bg-surface p-2 text-sm"/><label className="mt-2 flex gap-2 text-xs"><input required type="checkbox" name="confirmation" value="REJECT_SUGGESTION"/>Confirm rejection</label><button className="mt-2 rounded bg-loss px-3 py-2 text-sm font-bold text-white">Reject</button></form>
          <form action={mergeSuggestion} className="rounded-lg border border-border p-3"><input type="hidden" name="id" value={suggestion.id}/><select name="target_id" required className="w-full rounded border border-border bg-surface p-2 text-sm"><option value="">Merge into…</option>{suggestions.filter((item) => item.id !== suggestion.id && ["pending","approved"].includes(item.status)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><label className="mt-2 flex gap-2 text-xs"><input required type="checkbox" name="confirmation" value="MERGE_SUGGESTION"/>Confirm source merge</label><button className="mt-2 rounded bg-gold px-3 py-2 text-sm font-bold text-white">Merge</button></form>
        </div>}
      </Card>)}
      {!visible.length && <Card><p className="text-center text-sm text-muted">No suggestions match this queue.</p></Card>}
    </div>
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted">{label}</p><p className="font-semibold">{value}</p></div>; }
function EditNumber({ name, label, value, min, max, step = 0.1 }: { name: string; label: string; value: number; min: number; max: number; step?: number }) { return <label className="block text-xs">{label}<input name={name} type="number" defaultValue={value} min={min} max={max} step={step} required className="mt-1 w-full rounded border border-border bg-surface p-2 text-sm"/></label>; }
