import type { Achievement, AchievementCategory } from "@/types/database";
import { createHash } from "crypto";
import { getAchievementRarity } from "@/lib/achievements/rarity";

export interface AchievementSeedRow {
  code: string;
  name: string;
  description: string;
  howToUnlock: string;
  category: AchievementCategory;
  points: number;
  icon: string;
  requirement_type: string;
  requirement_value: Record<string, unknown>;
  is_hidden: boolean;
}

export const ACHIEVEMENT_SEED: AchievementSeedRow[] = [
  {
    code: "FIRST_TRADE",
    name: "First Trade",
    description: "Complete your first trade.",
    howToUnlock: "Buy or sell any asset.",
    category: "Getting Started",
    points: 10,
    icon: "📊",
    requirement_type: "trade_count",
    requirement_value: { count: 1 },
    is_hidden: false,
  },
  {
    code: "FIRST_BUY",
    name: "First Buy",
    description: "Buy your first asset.",
    howToUnlock: "Place a buy order on any asset.",
    category: "Getting Started",
    points: 10,
    icon: "🛒",
    requirement_type: "buy_count",
    requirement_value: { count: 1 },
    is_hidden: false,
  },
  {
    code: "FIRST_PROFIT",
    name: "First Profit",
    description: "Hold an asset with positive profit.",
    howToUnlock: "Own shares worth more than you paid.",
    category: "Getting Started",
    points: 25,
    icon: "💰",
    requirement_type: "profitable_holding",
    requirement_value: { count: 1 },
    is_hidden: false,
  },
  {
    code: "ACTIVE_TRADER",
    name: "Active Trader",
    description: "Complete 10 trades.",
    howToUnlock: "Buy or sell assets 10 times.",
    category: "Trading",
    points: 50,
    icon: "⚡",
    requirement_type: "trade_count",
    requirement_value: { count: 10 },
    is_hidden: false,
  },
  {
    code: "MARKET_REGULAR",
    name: "Market Regular",
    description: "Complete 50 trades.",
    howToUnlock: "Buy or sell assets 50 times.",
    category: "Trading",
    points: 100,
    icon: "📈",
    requirement_type: "trade_count",
    requirement_value: { count: 50 },
    is_hidden: false,
  },
  {
    code: "POWER_TRADER",
    name: "Power Trader",
    description: "Complete 100 trades.",
    howToUnlock: "Buy or sell assets 100 times.",
    category: "Trading",
    points: 250,
    icon: "🔥",
    requirement_type: "trade_count",
    requirement_value: { count: 100 },
    is_hidden: false,
  },
  {
    code: "PORTFOLIO_BUILDER",
    name: "Portfolio Builder",
    description: "Own 5 different assets.",
    howToUnlock: "Own 5 different assets.",
    category: "Portfolio",
    points: 50,
    icon: "🧱",
    requirement_type: "unique_assets",
    requirement_value: { count: 5 },
    is_hidden: false,
  },
  {
    code: "DIVERSIFIED",
    name: "Diversified",
    description: "Own assets in 3 different categories.",
    howToUnlock: "Own assets in 3 different categories.",
    category: "Portfolio",
    points: 75,
    icon: "🎨",
    requirement_type: "unique_categories",
    requirement_value: { count: 3 },
    is_hidden: false,
  },
  {
    code: "CULTURE_FUND",
    name: "Culture Fund",
    description: "Own assets in 6 different categories.",
    howToUnlock: "Own assets in 6 different categories.",
    category: "Portfolio",
    points: 150,
    icon: "🏛️",
    requirement_type: "unique_categories",
    requirement_value: { count: 6 },
    is_hidden: false,
  },
  {
    code: "BIG_PORTFOLIO",
    name: "Big Portfolio",
    description: "Build a seven-figure cultural portfolio.",
    howToUnlock: "Grow your total portfolio value to 1,000,000 DAQ.",
    category: "Portfolio",
    points: 250,
    icon: "💼",
    requirement_type: "portfolio_value",
    requirement_value: { value: 1_000_000 },
    is_hidden: false,
  },
  {
    code: "MARKET_MOGUL",
    name: "Market Mogul",
    description: "Join the elite ranks of CultureDAQ's wealthiest traders.",
    howToUnlock: "Grow your total portfolio value to 5,000,000 DAQ.",
    category: "Portfolio",
    points: 500,
    icon: "👑",
    requirement_type: "portfolio_value",
    requirement_value: { value: 5_000_000 },
    is_hidden: false,
  },
  {
    code: "CULTURE_TITAN",
    name: "Culture Titan",
    description: "Build a cultural empire worth 10 million DAQ.",
    howToUnlock: "Grow your total portfolio value to 10,000,000 DAQ.",
    category: "Portfolio",
    points: 1000,
    icon: "👑",
    requirement_type: "portfolio_value",
    requirement_value: { value: 10_000_000 },
    is_hidden: false,
  },
  {
    code: "TREND_SPOTTER",
    name: "Trend Spotter",
    description: "Own an asset before it reaches the Top 50.",
    howToUnlock: "Own an asset before it reaches the Top 50.",
    category: "Discovery",
    points: 75,
    icon: "🔭",
    requirement_type: "discovery_rank",
    requirement_value: { rank: 50 },
    is_hidden: false,
  },
  {
    code: "TALENT_SCOUT",
    name: "Talent Scout",
    description: "Own an asset before it reaches the Top 25.",
    howToUnlock: "Own an asset before it reaches the Top 25.",
    category: "Discovery",
    points: 150,
    icon: "🎯",
    requirement_type: "discovery_rank",
    requirement_value: { rank: 25 },
    is_hidden: false,
  },
  {
    code: "CULTURAL_ORACLE",
    name: "Cultural Oracle",
    description: "Predict a cultural breakout before the market notices.",
    howToUnlock: "Own an asset before it reaches the Top 10.",
    category: "Discovery",
    points: 500,
    icon: "🔮",
    requirement_type: "discovery_rank",
    requirement_value: { rank: 10 },
    is_hidden: false,
  },
  {
    code: "KINGMAKER",
    name: "Kingmaker",
    description: "Back a future market leader before anyone else.",
    howToUnlock: "Own an asset before it reaches #1 on the market.",
    category: "Discovery",
    points: 1000,
    icon: "👑",
    requirement_type: "discovery_rank",
    requirement_value: { rank: 1 },
    is_hidden: false,
  },
  {
    code: "TOP_100_TRADER",
    name: "Top 100 Trader",
    description: "Reach the Top 100 on the leaderboard.",
    howToUnlock: "Reach the Top 100 on the leaderboard.",
    category: "Rankings",
    points: 100,
    icon: "🏅",
    requirement_type: "leaderboard_rank",
    requirement_value: { rank: 100 },
    is_hidden: false,
  },
  {
    code: "TOP_25_TRADER",
    name: "Top 25 Trader",
    description: "Reach the Top 25 on the leaderboard.",
    howToUnlock: "Reach the Top 25 on the leaderboard.",
    category: "Rankings",
    points: 250,
    icon: "🥈",
    requirement_type: "leaderboard_rank",
    requirement_value: { rank: 25 },
    is_hidden: false,
  },
  {
    code: "TOP_10_TRADER",
    name: "Top 10 Trader",
    description: "Reach the Top 10 on the leaderboard.",
    howToUnlock: "Reach the Top 10 on the leaderboard.",
    category: "Rankings",
    points: 500,
    icon: "🥇",
    requirement_type: "leaderboard_rank",
    requirement_value: { rank: 10 },
    is_hidden: false,
  },
  {
    code: "NUMBER_ONE",
    name: "Number One",
    description: "Become the highest ranked trader in CultureDAQ.",
    howToUnlock: "Reach #1 on the leaderboard.",
    category: "Rankings",
    points: 1500,
    icon: "🏆",
    requirement_type: "leaderboard_rank",
    requirement_value: { rank: 1 },
    is_hidden: false,
  },
  {
    code: "MOVIE_BUFF",
    name: "Movie Buff",
    description: "Own 5 movie assets.",
    howToUnlock: "Own 5 assets in the Movies category.",
    category: "Categories",
    points: 75,
    icon: "🎬",
    requirement_type: "category_holdings",
    requirement_value: { category: "movies", count: 5 },
    is_hidden: false,
  },
  {
    code: "MUSIC_MOGUL",
    name: "Music Mogul",
    description: "Own 5 musician assets.",
    howToUnlock: "Own 5 assets in the Musicians category.",
    category: "Categories",
    points: 75,
    icon: "🎵",
    requirement_type: "category_holdings",
    requirement_value: { category: "musicians", count: 5 },
    is_hidden: false,
  },
  {
    code: "SPORTS_FANATIC",
    name: "Sports Fanatic",
    description: "Own 5 sports team assets.",
    howToUnlock: "Own 5 assets in the Sports Teams category.",
    category: "Categories",
    points: 75,
    icon: "⚽",
    requirement_type: "category_holdings",
    requirement_value: { category: "sports_teams", count: 5 },
    is_hidden: false,
  },
  {
    code: "BRAND_BUILDER",
    name: "Brand Builder",
    description: "Own 5 brand assets.",
    howToUnlock: "Own 5 assets in the Brands category.",
    category: "Categories",
    points: 75,
    icon: "🏷️",
    requirement_type: "category_holdings",
    requirement_value: { category: "brands", count: 5 },
    is_hidden: false,
  },
  {
    code: "STAR_COLLECTOR",
    name: "Star Collector",
    description: "Own 5 actor assets.",
    howToUnlock: "Own 5 assets in the Actors category.",
    category: "Categories",
    points: 75,
    icon: "⭐",
    requirement_type: "category_holdings",
    requirement_value: { category: "actors", count: 5 },
    is_hidden: false,
  },
  {
    code: "HOT_STREAK",
    name: "Hot Streak",
    description: "Have 3 profitable holdings at once.",
    howToUnlock: "Have 3 holdings in profit at the same time.",
    category: "Streaks",
    points: 150,
    icon: "🔥",
    requirement_type: "profitable_holdings",
    requirement_value: { count: 3 },
    is_hidden: false,
  },
  {
    code: "GREEN_PORTFOLIO",
    name: "Green Portfolio",
    description: "Have every holding in profit.",
    howToUnlock: "Make sure every asset you hold is in profit.",
    category: "Streaks",
    points: 200,
    icon: "💚",
    requirement_type: "all_holdings_profitable",
    requirement_value: {},
    is_hidden: false,
  },
  {
    code: "EARLY_ADOPTER",
    name: "Early Adopter",
    description: "Unlocked for early CultureDAQ users.",
    howToUnlock: "Join CultureDAQ during the early adopter period.",
    category: "Special",
    points: 100,
    icon: "🎯",
    requirement_type: "early_adopter",
    requirement_value: {},
    is_hidden: false,
  },
  {
    code: "DIAMOND_HANDS",
    name: "Diamond Hands",
    description: "Hold the same asset for 30 days.",
    howToUnlock: "Hold the same asset for 30 days.",
    category: "Special",
    points: 250,
    icon: "💎",
    requirement_type: "hold_days",
    requirement_value: { days: 30 },
    is_hidden: false,
  },
  {
    code: "CONTRARIAN",
    name: "Contrarian",
    description: "Buy an asset while it is down and later profit from it.",
    howToUnlock: "Buy an asset while its price is down, then hold until you profit.",
    category: "Special",
    points: 300,
    icon: "🔄",
    requirement_type: "contrarian",
    requirement_value: {},
    is_hidden: false,
  },
  {
    code: "PERFECT_TIMING",
    name: "Perfect Timing",
    description: "Buy an asset within 24 hours before it becomes a Top 10 asset.",
    howToUnlock: "Buy an asset shortly before it breaks into the Top 10.",
    category: "Special",
    points: 500,
    icon: "⏱️",
    requirement_type: "perfect_timing",
    requirement_value: {},
    is_hidden: false,
  },
];

const HOW_TO_UNLOCK_BY_CODE = Object.fromEntries(
  ACHIEVEMENT_SEED.map((row) => [row.code, row.howToUnlock])
) as Record<string, string>;

export function getHowToUnlock(code: string, fallback?: string): string {
  return HOW_TO_UNLOCK_BY_CODE[code] ?? fallback ?? "Keep playing to unlock this achievement.";
}

export function seedIdFromCode(code: string): string {
  const hash = createHash("sha256").update(`culture-daq-achievement:${code}`).digest("hex");
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    "4" + hash.slice(13, 16),
    hash.slice(16, 20),
    hash.slice(20, 32),
  ].join("-");
}

export function seedRowToAchievement(row: AchievementSeedRow): Achievement {
  return {
    id: seedIdFromCode(row.code),
    code: row.code,
    name: row.name,
    description: row.description,
    category: row.category,
    points: row.points,
    icon: row.icon,
    requirement_type: row.requirement_type,
    requirement_value: row.requirement_value,
    is_hidden: row.is_hidden,
    rarity: getAchievementRarity(row.code),
    scope: "standard",
    season_id: null,
    event_id: null,
    league_id: null,
    available_from: null,
    available_until: null,
    created_at: "1970-01-01T00:00:00.000Z",
  };
}

export function getStaticAchievementsCatalog(): Achievement[] {
  return ACHIEVEMENT_SEED.map(seedRowToAchievement);
}

export const ACHIEVEMENT_SEED_COUNT = ACHIEVEMENT_SEED.length;
