INSERT INTO assets (slug, name, category, description, current_price, previous_price, volatility_score, category_weight, featured, trading_paused, buy_pressure, sell_pressure, momentum_score, trade_volume_24h) VALUES
('lionel-messi', 'Lionel Messi', 'athletes'::asset_category, 'World Cup winner and football GOAT contender.', 445, 445, 1, 1.4, true, false, 0, 0, 0, 106),
('cristiano-ronaldo', 'Cristiano Ronaldo', 'athletes'::asset_category, 'Global football icon with massive social reach.', 420.75, 420.75, 1.1, 1, true, false, 0, 0, 0, 24),
('lebron-james', 'LeBron James', 'athletes'::asset_category, 'NBA legend and cultural powerhouse.', 398.5, 398.5, 0.9, 1, false, false, 0, 0, 0, 97),
('max-verstappen', 'Max Verstappen', 'athletes'::asset_category, 'F1 world champion with devoted fan army.', 312, 312, 1.3, 1, false, false, 0, 0, 0, 54),
('erling-haaland', 'Erling Haaland', 'athletes'::asset_category, 'Goal machine dominating European football.', 289.25, 289.25, 1.2, 1, false, false, 0, 0, 0, 160),
('simone-biles', 'Simone Biles', 'athletes'::asset_category, 'Gymnastics GOAT and mental health advocate.', 267.5, 267.5, 1, 1, false, false, 0, 0, 0, 65),
('patrick-mahomes', 'Patrick Mahomes', 'athletes'::asset_category, 'NFL superstar quarterback.', 301, 301, 1.1, 1, false, false, 0, 0, 0, 110),
('naomi-osaka', 'Naomi Osaka', 'athletes'::asset_category, 'Tennis champion and cultural voice.', 198.75, 198.75, 1.2, 1, false, false, 0, 0, 0, 169),
('kylian-mbappe', 'Kylian Mbappé', 'athletes'::asset_category, 'French football prodigy and global brand.', 356, 356, 1.2, 1, false, false, 0, 0, 0, 154),
('stephen-curry', 'Stephen Curry', 'athletes'::asset_category, 'NBA sharpshooter and global brand.', 278.5, 278.5, 1.1, 1, false, false, 0, 0, 0, 171),
('mrbeast', 'MrBeast', 'influencers'::asset_category, 'YouTube''s biggest creator and philanthropist.', 389, 389, 1.3, 1, true, false, 0, 0, 0, 27),
('ksi', 'KSI', 'influencers'::asset_category, 'YouTuber, boxer, and music artist.', 245.5, 245.5, 1.5, 1, false, false, 0, 0, 0, 20),
('charli-damelio', 'Charli D''Amelio', 'influencers'::asset_category, 'TikTok''s most-followed dancer.', 212.75, 212.75, 1.4, 1, false, false, 0, 0, 0, 46),
('emma-chamberlain', 'Emma Chamberlain', 'influencers'::asset_category, 'Relatable creator turned fashion fixture.', 198, 198, 1.2, 1, false, false, 0, 0, 0, 120),
('khaby-lame', 'Khaby Lame', 'influencers'::asset_category, 'Silent comedy king of TikTok.', 234.25, 234.25, 1.3, 1, false, false, 0, 0, 0, 137),
('addison-rae', 'Addison Rae', 'influencers'::asset_category, 'TikTok star crossing into film and music.', 167.5, 167.5, 1.4, 1, false, false, 0, 0, 0, 150),
('logan-paul', 'Logan Paul', 'influencers'::asset_category, 'Controversial creator and Prime co-founder.', 278, 278, 1.6, 1, false, false, 0, 0, 0, 165),
('pewdiepie', 'PewDiePie', 'influencers'::asset_category, 'OG YouTube legend with loyal following.', 256.75, 256.75, 1, 1, false, false, 0, 0, 0, 182),
('gordon-ramsay', 'Gordon Ramsay', 'tv_personalities'::asset_category, 'Michelin-star chef and reality TV icon.', 298.5, 298.5, 1.1, 1, true, false, 0, 0, 0, 137),
('oprah-winfrey', 'Oprah Winfrey', 'tv_personalities'::asset_category, 'Media mogul and cultural institution.', 367, 367, 0.8, 1, false, false, 0, 0, 0, 58) ON CONFLICT (slug) DO NOTHING;