INSERT INTO assets (slug, name, category, description, current_price, previous_price, volatility_score, category_weight, featured, trading_paused, buy_pressure, sell_pressure, momentum_score, trade_volume_24h) VALUES
('tom-holland', 'Tom Holland', 'actors'::asset_category, 'Spider-Man star and rising Hollywood leading man.', 245.5, 245.5, 1.2, 1, true, false, 0, 0, 0, 144),
('zendaya', 'Zendaya', 'actors'::asset_category, 'Emmy-winning actress and global fashion icon.', 312.75, 312.75, 1.1, 1, true, false, 0, 0, 0, 141),
('timothee-chalamet', 'Timothée Chalamet', 'actors'::asset_category, 'Critically acclaimed actor with massive Gen Z appeal.', 278, 278, 1.3, 1, false, false, 0, 0, 0, 181),
('florence-pugh', 'Florence Pugh', 'actors'::asset_category, 'Versatile actress known for bold performances.', 198.25, 198.25, 1.2, 1, false, false, 0, 0, 0, 6),
('pedro-pascal', 'Pedro Pascal', 'actors'::asset_category, 'Star of The Mandalorian, The Last of Us, and blockbuster films.', 265, 265, 1.4, 1, true, false, 0, 0, 0, 52),
('jenna-ortega', 'Jenna Ortega', 'actors'::asset_category, 'Wednesday star with horror and comedy range.', 189.5, 189.5, 1.3, 1, false, false, 0, 0, 0, 13),
('austin-butler', 'Austin Butler', 'actors'::asset_category, 'Elvis breakout with growing filmography.', 156.75, 156.75, 1.1, 1, false, false, 0, 0, 0, 72),
('margot-robbie', 'Margot Robbie', 'actors'::asset_category, 'Producer and star with box office power.', 287, 287, 1, 1, false, false, 0, 0, 0, 99),
('ryan-gosling', 'Ryan Gosling', 'actors'::asset_category, 'Oscar-nominated actor from La La Land, Barbie, and Drive.', 234.5, 234.5, 1, 1, false, false, 0, 0, 0, 140),
('cillian-murphy', 'Cillian Murphy', 'actors'::asset_category, 'Oscar winner riding peak prestige momentum.', 221, 221, 1.1, 1, false, false, 0, 0, 0, 1),
('taylor-swift', 'Taylor Swift', 'musicians'::asset_category, 'Global pop phenomenon and touring powerhouse.', 485, 485, 1, 1.5, true, false, 0, 0, 0, 81),
('drake', 'Drake', 'musicians'::asset_category, 'Chart-dominating rapper and cultural fixture.', 356.25, 356.25, 1.2, 1, true, false, 0, 0, 0, 135),
('billie-eilish', 'Billie Eilish', 'musicians'::asset_category, 'Grammy-winning artist with devoted fanbase.', 298.5, 298.5, 1.1, 1, false, false, 0, 0, 0, 178),
('sabrina-carpenter', 'Sabrina Carpenter', 'musicians'::asset_category, 'Pop star on a meteoric rise.', 267.75, 267.75, 1.5, 1, true, false, 0, 0, 0, 97),
('beyonce', 'Beyoncé', 'musicians'::asset_category, 'Queen Bey — icon status across generations.', 412, 412, 0.9, 1, false, false, 0, 0, 0, 118),
('bad-bunny', 'Bad Bunny', 'musicians'::asset_category, 'Global Latin trap superstar.', 334.5, 334.5, 1.3, 1, false, false, 0, 0, 0, 159),
('olivia-rodrigo', 'Olivia Rodrigo', 'musicians'::asset_category, 'Gen Z pop sensation with raw songwriting.', 245, 245, 1.4, 1, false, false, 0, 0, 0, 71),
('the-weeknd', 'The Weeknd', 'musicians'::asset_category, 'R&B megastar with cinematic visuals.', 289.25, 289.25, 1, 1, false, false, 0, 0, 0, 66),
('dua-lipa', 'Dua Lipa', 'musicians'::asset_category, 'Dance-pop hitmaker with global reach.', 256, 256, 1.1, 1, false, false, 0, 0, 0, 106),
('kendrick-lamar', 'Kendrick Lamar', 'musicians'::asset_category, 'Pulitzer Prize-winning hip-hop visionary.', 378.5, 378.5, 1.2, 1, false, false, 0, 0, 0, 143) ON CONFLICT (slug) DO NOTHING;